/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("properties");

  const record0 = new Record(collection);
    record0.set("hostId", "demo_host_001");
    record0.set("title", "Riverside Villa Dehradun");
    record0.set("location", "Dehradun, Riverside");
    record0.set("propertyType", "villa");
    record0.set("pricePerNight", 4500);
    record0.set("description", "Beautiful riverside villa with modern amenities and garden views. Perfect for families and groups seeking a peaceful retreat near Dehradun.");
    record0.set("rating", 4.8);
    record0.set("propertyCategory", "Villa");
    record0.set("approvalStatus", "approved");
    record0.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("hostId", "demo_host_002");
    record1.set("title", "Luxury Mountain Home");
    record1.set("location", "Dehradun, Mussoorie Road");
    record1.set("propertyType", "villa");
    record1.set("pricePerNight", 6500);
    record1.set("description", "Spacious luxury villa with panoramic mountain views, private pool, and modern kitchen. Ideal for a luxurious mountain getaway.");
    record1.set("rating", 4.9);
    record1.set("propertyCategory", "Villa");
    record1.set("approvalStatus", "approved");
    record1.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}]);
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("hostId", "demo_host_003");
    record2.set("title", "Cozy BnB near Mall Road");
    record2.set("location", "Dehradun, Mall Road");
    record2.set("propertyType", "room");
    record2.set("pricePerNight", 2500);
    record2.set("description", "Charming BnB in the heart of Dehradun near shopping and dining. Comfortable rooms with warm hospitality.");
    record2.set("rating", 4.6);
    record2.set("propertyCategory", "BnB");
    record2.set("approvalStatus", "approved");
    record2.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("hostId", "demo_host_004");
    record3.set("title", "Forest View Resort");
    record3.set("location", "Dehradun, Sahastradhara");
    record3.set("propertyType", "house");
    record3.set("pricePerNight", 5500);
    record3.set("description", "Serene resort surrounded by forests with excellent amenities. Great for nature lovers and adventure seekers.");
    record3.set("rating", 4.7);
    record3.set("propertyCategory", "Hotel");
    record3.set("approvalStatus", "approved");
    record3.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("hostId", "demo_host_005");
    record4.set("title", "Heritage Bungalow");
    record4.set("location", "Dehradun, Clement Town");
    record4.set("propertyType", "villa");
    record4.set("pricePerNight", 5000);
    record4.set("description", "Historic bungalow with colonial charm and modern comforts. Experience the elegance of old Dehradun.");
    record4.set("rating", 4.5);
    record4.set("propertyCategory", "Villa");
    record4.set("approvalStatus", "approved");
    record4.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("hostId", "demo_host_006");
    record5.set("title", "Budget Friendly Homestay");
    record5.set("location", "Dehradun, Rajpur Road");
    record5.set("propertyType", "room");
    record5.set("pricePerNight", 2000);
    record5.set("description", "Affordable and comfortable homestay with local hospitality. Perfect for budget travelers.");
    record5.set("rating", 4.4);
    record5.set("propertyCategory", "BnB");
    record5.set("approvalStatus", "approved");
    record5.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("hostId", "demo_host_007");
    record6.set("title", "Snow View Villa Shimla");
    record6.set("location", "Shimla, Kufri");
    record6.set("propertyType", "villa");
    record6.set("pricePerNight", 5500);
    record6.set("description", "Stunning villa with snow-capped mountain views and modern amenities. Perfect for winter getaways and family vacations.");
    record6.set("rating", 4.8);
    record6.set("propertyCategory", "Villa");
    record6.set("approvalStatus", "approved");
    record6.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='Heating'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Garden'"}]);
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("hostId", "demo_host_008");
    record7.set("title", "Heritage Hotel Shimla");
    record7.set("location", "Shimla, Mall Road");
    record7.set("propertyType", "house");
    record7.set("pricePerNight", 8000);
    record7.set("description", "Luxurious heritage hotel in the heart of Shimla with world-class amenities and service. Experience royal hospitality.");
    record7.set("rating", 4.9);
    record7.set("propertyCategory", "Hotel");
    record7.set("approvalStatus", "approved");
    record7.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("hostId", "demo_host_009");
    record8.set("title", "Cottage in the Clouds");
    record8.set("location", "Shimla, Mashobra");
    record8.set("propertyType", "room");
    record8.set("pricePerNight", 3500);
    record8.set("description", "Cozy cottage with cloud views and peaceful surroundings. Ideal for couples and small families.");
    record8.set("rating", 4.7);
    record8.set("propertyCategory", "BnB");
    record8.set("approvalStatus", "approved");
    record8.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Heating'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}]);
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("hostId", "demo_host_010");
    record9.set("title", "Pine Forest Villa");
    record9.set("location", "Shimla, Chharabra");
    record9.set("propertyType", "villa");
    record9.set("pricePerNight", 6500);
    record9.set("description", "Secluded villa nestled in pine forests with modern facilities. Perfect for a quiet mountain retreat.");
    record9.set("rating", 4.6);
    record9.set("propertyCategory", "Villa");
    record9.set("approvalStatus", "approved");
    record9.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Heating'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}, {"_lookup": "amenities", "where": "name='Garden'"}]);
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("hostId", "demo_host_011");
    record10.set("title", "Shimla Palace Hotel");
    record10.set("location", "Shimla, The Ridge");
    record10.set("propertyType", "house");
    record10.set("pricePerNight", 7500);
    record10.set("description", "Grand hotel with panoramic views of the Himalayas and excellent dining options. A true palace experience.");
    record10.set("rating", 4.8);
    record10.set("propertyCategory", "Hotel");
    record10.set("approvalStatus", "approved");
    record10.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("hostId", "demo_host_012");
    record11.set("title", "Mountain View BnB");
    record11.set("location", "Shimla, Sanjauli");
    record11.set("propertyType", "room");
    record11.set("pricePerNight", 3000);
    record11.set("description", "Charming BnB with mountain views and warm hospitality. Great base for exploring Shimla.");
    record11.set("rating", 4.5);
    record11.set("propertyCategory", "BnB");
    record11.set("approvalStatus", "approved");
    record11.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Heating'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record11);

  const record12 = new Record(collection);
    record12.set("hostId", "demo_host_013");
    record12.set("title", "Pink City Palace");
    record12.set("location", "Jaipur, C-Scheme");
    record12.set("propertyType", "villa");
    record12.set("pricePerNight", 7000);
    record12.set("description", "Magnificent villa inspired by Jaipur architecture with traditional design and modern luxury. Experience royal Rajasthan.");
    record12.set("rating", 4.9);
    record12.set("propertyCategory", "Villa");
    record12.set("approvalStatus", "approved");
    record12.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record12);

  const record13 = new Record(collection);
    record13.set("hostId", "demo_host_014");
    record13.set("title", "Rajasthani Heritage Villa");
    record13.set("location", "Jaipur, Nahargarh");
    record13.set("propertyType", "villa");
    record13.set("pricePerNight", 5000);
    record13.set("description", "Authentic Rajasthani villa with traditional decor and modern amenities. Perfect for experiencing local culture.");
    record13.set("rating", 4.7);
    record13.set("propertyCategory", "Villa");
    record13.set("approvalStatus", "approved");
    record13.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record13);

  const record14 = new Record(collection);
    record14.set("hostId", "demo_host_015");
    record14.set("title", "Modern City Apartment");
    record14.set("location", "Jaipur, Bani Park");
    record14.set("propertyType", "room");
    record14.set("pricePerNight", 3000);
    record14.set("description", "Contemporary apartment in a prime location with all modern facilities. Ideal for business travelers and tourists.");
    record14.set("rating", 4.6);
    record14.set("propertyCategory", "BnB");
    record14.set("approvalStatus", "approved");
    record14.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record14);

  const record15 = new Record(collection);
    record15.set("hostId", "demo_host_016");
    record15.set("title", "Fort View Resort");
    record15.set("location", "Jaipur, Amber");
    record15.set("propertyType", "house");
    record15.set("pricePerNight", 6500);
    record15.set("description", "Luxury resort with views of Amber Fort and traditional Rajasthani hospitality. A perfect blend of heritage and comfort.");
    record15.set("rating", 4.8);
    record15.set("propertyCategory", "Hotel");
    record15.set("approvalStatus", "approved");
    record15.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record15);

  const record16 = new Record(collection);
    record16.set("hostId", "demo_host_017");
    record16.set("title", "City Palace Hotel");
    record16.set("location", "Jaipur, Sanganeri Gate");
    record16.set("propertyType", "house");
    record16.set("pricePerNight", 7500);
    record16.set("description", "Upscale hotel near City Palace with excellent service and authentic Rajasthani cuisine. Experience royal Jaipur.");
    record16.set("rating", 4.9);
    record16.set("propertyCategory", "Hotel");
    record16.set("approvalStatus", "approved");
    record16.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record16);

  const record17 = new Record(collection);
    record17.set("hostId", "demo_host_018");
    record17.set("title", "Budget Haveli Stay");
    record17.set("location", "Jaipur, Johari Bazaar");
    record17.set("propertyType", "room");
    record17.set("pricePerNight", 2500);
    record17.set("description", "Affordable stay in a traditional haveli with authentic charm. Perfect for budget-conscious travelers.");
    record17.set("rating", 4.4);
    record17.set("propertyCategory", "BnB");
    record17.set("approvalStatus", "approved");
    record17.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record17);

  const record18 = new Record(collection);
    record18.set("hostId", "demo_host_019");
    record18.set("title", "Hilltop Resort Mussoorie");
    record18.set("location", "Mussoorie, Camel Back Road");
    record18.set("propertyType", "house");
    record18.set("pricePerNight", 9000);
    record18.set("description", "Premium hilltop resort with panoramic valley views and world-class amenities. Perfect for a luxurious mountain escape.");
    record18.set("rating", 4.9);
    record18.set("propertyCategory", "Hotel");
    record18.set("approvalStatus", "approved");
    record18.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}, {"_lookup": "amenities", "where": "name='Balcony'"}]);
  app.save(record18);

  const record19 = new Record(collection);
    record19.set("hostId", "demo_host_020");
    record19.set("title", "Valley View Villa");
    record19.set("location", "Mussoorie, Landour");
    record19.set("propertyType", "villa");
    record19.set("pricePerNight", 5500);
    record19.set("description", "Spacious villa with stunning valley views and modern facilities. Ideal for families and group getaways.");
    record19.set("rating", 4.8);
    record19.set("propertyCategory", "Villa");
    record19.set("approvalStatus", "approved");
    record19.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record19);

  const record20 = new Record(collection);
    record20.set("hostId", "demo_host_021");
    record20.set("title", "Budget BnB Mussoorie");
    record20.set("location", "Mussoorie, Mall Road");
    record20.set("propertyType", "room");
    record20.set("pricePerNight", 2800);
    record20.set("description", "Cozy and affordable BnB in the heart of Mussoorie. Great location for exploring the town.");
    record20.set("rating", 4.5);
    record20.set("propertyCategory", "BnB");
    record20.set("approvalStatus", "approved");
    record20.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record20);

  const record21 = new Record(collection);
    record21.set("hostId", "demo_host_022");
    record21.set("title", "Cloud Nine Villa");
    record21.set("location", "Mussoorie, Happy Valley");
    record21.set("propertyType", "villa");
    record21.set("pricePerNight", 6500);
    record21.set("description", "Luxurious villa with cloud views and premium amenities. Perfect for a romantic getaway.");
    record21.set("rating", 4.8);
    record21.set("propertyCategory", "Villa");
    record21.set("approvalStatus", "approved");
    record21.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Fireplace'"}, {"_lookup": "amenities", "where": "name='Garden'"}]);
  app.save(record21);

  const record22 = new Record(collection);
    record22.set("hostId", "demo_host_023");
    record22.set("title", "Mussoorie Grand Hotel");
    record22.set("location", "Mussoorie, The Mall");
    record22.set("propertyType", "house");
    record22.set("pricePerNight", 8500);
    record22.set("description", "Grand hotel with elegant rooms and excellent dining. A perfect base for exploring Mussoorie.");
    record22.set("rating", 4.9);
    record22.set("propertyCategory", "Hotel");
    record22.set("approvalStatus", "approved");
    record22.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record22);

  const record23 = new Record(collection);
    record23.set("hostId", "demo_host_024");
    record23.set("title", "Nature Retreat BnB");
    record23.set("location", "Mussoorie, Benog Road");
    record23.set("propertyType", "room");
    record23.set("pricePerNight", 3200);
    record23.set("description", "Peaceful BnB surrounded by nature with comfortable rooms. Ideal for nature lovers.");
    record23.set("rating", 4.6);
    record23.set("propertyCategory", "BnB");
    record23.set("approvalStatus", "approved");
    record23.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Garden'"}]);
  app.save(record23);

  const record24 = new Record(collection);
    record24.set("hostId", "demo_host_025");
    record24.set("title", "Jungle Lodge Jim Corbett");
    record24.set("location", "Jim Corbett, Ramnagar");
    record24.set("propertyType", "villa");
    record24.set("pricePerNight", 6500);
    record24.set("description", "Authentic jungle lodge with wildlife viewing opportunities and nature trails. Perfect for adventure and wildlife enthusiasts.");
    record24.set("rating", 4.8);
    record24.set("propertyCategory", "Villa");
    record24.set("approvalStatus", "approved");
    record24.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record24);

  const record25 = new Record(collection);
    record25.set("hostId", "demo_host_026");
    record25.set("title", "Wildlife Resort");
    record25.set("location", "Jim Corbett, Dhikuli");
    record25.set("propertyType", "house");
    record25.set("pricePerNight", 8500);
    record25.set("description", "Premium resort with safari facilities and expert guides. Experience the thrill of wildlife in comfort.");
    record25.set("rating", 4.9);
    record25.set("propertyCategory", "Hotel");
    record25.set("approvalStatus", "approved");
    record25.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record25);

  const record26 = new Record(collection);
    record26.set("hostId", "demo_host_027");
    record26.set("title", "Nature Cottage");
    record26.set("location", "Jim Corbett, Kanda");
    record26.set("propertyType", "room");
    record26.set("pricePerNight", 3200);
    record26.set("description", "Cozy cottage in the heart of nature with basic amenities. Perfect for budget wildlife enthusiasts.");
    record26.set("rating", 4.5);
    record26.set("propertyCategory", "BnB");
    record26.set("approvalStatus", "approved");
    record26.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Garden'"}]);
  app.save(record26);

  const record27 = new Record(collection);
    record27.set("hostId", "demo_host_028");
    record27.set("title", "Tiger View Villa");
    record27.set("location", "Jim Corbett, Bijrani");
    record27.set("propertyType", "villa");
    record27.set("pricePerNight", 7500);
    record27.set("description", "Exclusive villa with prime tiger viewing location and luxury amenities. A dream destination for wildlife lovers.");
    record27.set("rating", 4.9);
    record27.set("propertyCategory", "Villa");
    record27.set("approvalStatus", "approved");
    record27.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Balcony'"}, {"_lookup": "amenities", "where": "name='Garden'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record27);

  const record28 = new Record(collection);
    record28.set("hostId", "demo_host_029");
    record28.set("title", "Corbett Wilderness Resort");
    record28.set("location", "Jim Corbett, Garjiya");
    record28.set("propertyType", "house");
    record28.set("pricePerNight", 9000);
    record28.set("description", "Luxury wilderness resort with all modern facilities and expert naturalists. Experience untamed nature in style.");
    record28.set("rating", 4.9);
    record28.set("propertyCategory", "Hotel");
    record28.set("approvalStatus", "approved");
    record28.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='Kitchen'"}, {"_lookup": "amenities", "where": "name='Pool'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='Parking'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Gym'"}, {"_lookup": "amenities", "where": "name='Hot Tub'"}, {"_lookup": "amenities", "where": "name='Elevator'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='Laundry Service'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record28);

  const record29 = new Record(collection);
    record29.set("hostId", "demo_host_030");
    record29.set("title", "Budget Safari Lodge");
    record29.set("location", "Jim Corbett, Nainital Road");
    record29.set("propertyType", "room");
    record29.set("pricePerNight", 2800);
    record29.set("description", "Affordable lodge with safari access and basic amenities. Perfect for budget wildlife explorers.");
    record29.set("rating", 4.4);
    record29.set("propertyCategory", "BnB");
    record29.set("approvalStatus", "approved");
    record29.set("amenities", [{"_lookup": "amenities", "where": "name='WiFi'"}, {"_lookup": "amenities", "where": "name='AC'"}, {"_lookup": "amenities", "where": "name='TV'"}, {"_lookup": "amenities", "where": "name='Breakfast'"}, {"_lookup": "amenities", "where": "name='24/7 Security'"}]);
  app.save(record29);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})